name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - requests
  - warnings
  - pytz
  - pip
  - pip:
      - gridstatus
      - gridstatusio>=0.14.0
      - yfinance
