name: myenv
channels:
  - conda-forge

dependencies:
  - python=3.11
  - pandas
  - numpy
  - requests
  - pytz
  - yfinance
  - termcolor
  - pip
  - pip:
      - gridstatus==0.29.1
      - gridstatusio==0.5.6
