name: myenv
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - numpy
  - requests
  - pytz
  - pip
  - pip:
      - gridstatus==0.29.1
      - gridstatusio
      - termcolor
      - yfinance
