name: Daily Conda Job

on:
  schedule:
    # Runs daily at 4:30 AM UTC
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Setup Miniconda and activate environment from environment.yml
      - name: Setup Conda and activate environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          environment-file: environment.yml
          activate-environment: myenv
          python-version: '3.11'
          channels: conda-forge,defaults
          auto-activate-base: false
          miniforge-version: latest
          use-only-miniforge: true

     # - name: Run Python script
        # The 'conda run' command is no longer needed because the environment is already activated
        #run: python mainPipe.py
