# Fixes your workflow to manually cache the Conda environment.

name: Daily Conda Job

on:
  schedule:
    # Runs daily at 4:30 AM UTC
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Manually set up Conda and its location on the runner.
      - name: Set up Conda on runner
        # Use an action that just installs Conda without managing environments.
        uses: mamba-org/setup-micromamba@v1
        with:
          micromamba-version: latest
          init-shell: bash

      # --- Caching Steps ---
      # This block handles caching the Conda environment directory.
      # The 'key' uses the hash of environment.yml to invalidate the cache
      # if dependencies change.
      - name: Cache Conda environment
        id: cache-conda
        uses: actions/cache@v4
        with:
          path: D:\a\Daily-Conda-Job\Daily-Conda-Job\.micromamba\envs\myenv
          key: ${{ runner.os }}-conda-env-${{ hashFiles('environment.yml') }}
          restore-keys: |
            ${{ runner.os }}-conda-env-

      # This is the conditional step to create the environment.
      # It runs only if the cache was a miss (no existing environment found).
      - name: Create Conda environment
        if: steps.cache-conda.outputs.cache-hit != 'true'
        shell: bash
        run: |
          micromamba env create -f environment.yml -n myenv

      # --- Run Script ---
      # Run your Python script using the activated environment.
      #- name: Run Python script
      #  shell: bash
       # run: |
       #   micromamba activate myenv
        #  python mainPipe.py
