name: Daily Conda Job

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  caching-example:
    name: Caching
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this to reset cache even if environment.yml hasn’t changed
          CACHE_NUMBER: 0
        with:
          path: C:\Users\runneradmin\conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: myenv
          environment-file: environment.yml
          channel-priority: strict
          use-only-tar-bz2: true # IMPORTANT for cache re-use!
          auto-update-conda: true

     # - name: Run pipeline
      #  shell: bash -l {0}
      #  run: |
       #   conda activate myenv
       #   python mainPipe.py
