name: Daily Conda Job

on:
  schedule:
    - cron: '30 4 * * *'
  workflow_dispatch:

jobs:
  caching-example:
    name: Caching
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0               # get full history
          ref: ${{ github.ref }}       # check out the branch that triggered workflow

      - name: Cache conda
        uses: actions/cache@v3
        env:
          # Increase this to reset cache even if environment.yml hasn’t changed
          CACHE_NUMBER: 0
        with:
          path: C:\Users\runneradmin\conda_pkgs_dir
          key: ${{ runner.os }}-conda-${{ env.CACHE_NUMBER }}-${{ hashFiles('environment.yml') }}

      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: myenv
          environment-file: environment.yml
          channel-priority: strict
          use-only-tar-bz2: true # IMPORTANT for cache re-use!
          auto-update-conda: true

      - name: Run pipeline
        shell: bash -l {0}
        run: |
          conda activate myenv
          python mainPipe.py

      - name: Commit and push CSVs
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          git add *.csv
          git commit -m "Add generated CSVs [skip ci]" || echo "No changes to commit"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
