name: Daily Conda Job

on:
  schedule:
    # Runs daily at 11:30 PM UTC
    - cron: '30 4 * * *'
  workflow_dispatch: # allows manual triggering

jobs:
  run-script:
    runs-on: windows-latest

    steps:
      # 1. Checkout your code
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Set up Miniconda
      - name: Set up Miniconda
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: myenv
          python-version: 3.11
          channels: conda-forge
          environment-file: environment.yml
          auto-activate-base: false


      # 3. Run your Python script
      - name: Run Python script
        shell: bash
        run: |
          conda run -n myenv python mainPipe.py
