name: Daily Conda Job

on:
  schedule:
    - cron: '10 22 * * *'
  workflow_dispatch:

jobs:
  caching-example:
    name: Caching
    runs-on: windows-latest
    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0               # Get full history
          ref: ${{ github.ref }}       # Check out the branch that triggered workflow

      - name: Cache Conda packages and environment
        uses: actions/cache@v4
        with:
          path: |
            C:\Users\runneradmin\conda_pkgs_dir
            C:\Users\runneradmin\miniconda3\pkgs
            C:\Users\runneradmin\miniconda3\envs\myenv
          key: ${{ runner.os }}-conda-${{ hashFiles('environment.yml') }}-v1
          restore-keys: |
            ${{ runner.os }}-conda-
        env:
          # Bump this to invalidate cache manually if needed
          CACHE_NUMBER: 0

      - name: Set up Conda environment
        uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: myenv
          environment-file: environment.yml
          use-mamba: true
          clean-package-cache: false
          channel-priority: strict
          use-only-tar-bz2: true        # Ensure cache compatibility
          auto-update-conda: false
          auto-activate-base: false     # Avoid auto_activate_base warning

      # - name: Run pipeline
      #   shell: bash -l {0}
      #   run: |
      #     conda activate myenv
      #     python mainPipe.py

      # - name: Commit and push CSVs
      #   run: |
      #     git config --global user.name "github-actions[bot]"
      #     git config --global user.email "github-actions[bot]@users.noreply.github.com"
      #     git add *.csv
      #     git commit -m "Add generated CSVs [skip ci]" || echo "No changes to commit"
      #     git push
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
